[package]
name = "bouncing-square"
version = "0.1.0"
authors = ["Carlos Iriarte <ciriarte@gmail.com>"]

[[bin]]
name = "bouncing-square"

[dependencies]
piston = "0.26.0"
piston2d-graphics = "0.18.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.35.0"